FROM golang:1.16-alpine3.15 as builder

RUN apk add --no-cache git

WORKDIR /src
RUN git clone https://github.com/boxboat/fixuid 

WORKDIR /src/fixuid
RUN git checkout -b work v0.5.1
RUN ./build.sh

############
FROM ubuntu:@UBUNTU_VERSION@

ARG USER=@USER@
ARG USER_ID=1000
ARG GROUP=@GROUP@
ARG GROUP_ID=1000
ENV FIXUID=/usr/local/bin/fixuid

# Create new user
RUN \
    addgroup --gid ${GROUP_ID} ${GROUP} && \
    adduser --uid ${USER_ID} --ingroup ${GROUP} --disabled-password --gecos "" ${USER}

COPY --from=builder /src/fixuid/fixuid ${FIXUID}
RUN \
    chown root:root ${FIXUID} && \
    chmod 4755 ${FIXUID} && \
    mkdir -p /etc/fixuid && \
    printf "user: ${USER}\ngroup: ${GROUP}\n" > /etc/fixuid/config.yml

ENTRYPOINT ["/usr/local/bin/fixuid"]

